Repository APRO-Project/app, pull requests merged in 2020-01, with the labels that each got.

#21 Ordinary piece move logic implementation
  app/src/main/java/com/cyberbot/checkers/game/Grid.java
  app/src/main/java/com/cyberbot/checkers/game/GridEntry.java
  app/src/main/java/com/cyberbot/checkers/game/PieceType.java
  app/src/main/java/com/cyberbot/checkers/ui/activity/GameActivity.kt
  app/src/test/java/com/cyberbot/checkers/game/GridTest.java
Labels: enhancement

#26 Implemented ordinary piece captures
  app/src/main/java/com/cyberbot/checkers/game/CaptureChain.java
  app/src/main/java/com/cyberbot/checkers/game/Grid.java
  app/src/main/java/com/cyberbot/checkers/game/GridEntry.java
  app/src/main/java/com/cyberbot/checkers/ui/activity/GameActivity.kt
  app/src/main/java/com/cyberbot/checkers/ui/view/CheckersGridView.kt
Labels: enhancement

#31 Improved moves calculation
  app/src/main/java/com/cyberbot/checkers/game/CaptureChain.java
  app/src/main/java/com/cyberbot/checkers/game/Destination.java
  app/src/main/java/com/cyberbot/checkers/game/Grid.java
  app/src/main/java/com/cyberbot/checkers/game/GridEntry.java
  app/src/main/java/com/cyberbot/checkers/ui/activity/GameActivity.kt
  app/src/main/java/com/cyberbot/checkers/ui/activity/SettingsActivity.kt
  app/src/main/java/com/cyberbot/checkers/ui/view/CheckersGridView.kt
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/test/java/com/cyberbot/checkers/game/GridTest.java
Labels: enhancement

#42 Connect AI to UI
  app/build.gradle
  app/src/main/java/com/cyberbot/checkers/game/AiPlayer.java
  app/src/main/java/com/cyberbot/checkers/game/Grid.java
  app/src/main/java/com/cyberbot/checkers/game/GridEntry.java
  app/src/main/java/com/cyberbot/checkers/game/Node.java
  app/src/main/java/com/cyberbot/checkers/ui/activity/GameActivity.kt
Labels: enhancement

#45 Improved javadocs and annotations
  app/src/main/java/com/cyberbot/checkers/game/CaptureChain.java
  app/src/main/java/com/cyberbot/checkers/game/Destination.java
  app/src/main/java/com/cyberbot/checkers/game/Grid.java
  app/src/main/java/com/cyberbot/checkers/game/GridEntry.java
  app/src/main/java/com/cyberbot/checkers/ui/view/CheckersGridView.kt
  app/src/test/java/com/cyberbot/checkers/game/GridTest.java
Labels: enhancement

#47 King moves
  app/src/main/java/com/cyberbot/checkers/game/Grid.java
  app/src/test/java/com/cyberbot/checkers/game/GridTest.java
Labels: enhancement

#50 UI Improvements
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cyberbot/checkers/game/Grid.java
  app/src/main/java/com/cyberbot/checkers/ui/activity/GameActivity.kt
  app/src/main/java/com/cyberbot/checkers/ui/activity/SettingsActivity.kt
  app/src/main/res/layout/activity_settings.xml
Labels: bug, enhancement

#48 Fix/ai-move-preferences
  app/build.gradle
  app/src/main/java/com/cyberbot/checkers/game/AiPlayer.java
  app/src/main/java/com/cyberbot/checkers/game/Grid.java
Labels: bug

#51 King captures
  app/src/main/java/com/cyberbot/checkers/game/CaptureChain.java
  app/src/main/java/com/cyberbot/checkers/game/Grid.java
Labels: enhancement

#52 Piece promotions
  app/src/main/java/com/cyberbot/checkers/game/Grid.java
Labels: enhancement

#53 Fix/ai king support
  app/src/main/java/com/cyberbot/checkers/game/Grid.java
Labels: bug, enhancement

#54 Code improvements 2
  app/src/main/java/com/cyberbot/checkers/ui/activity/GameActivity.kt
  app/src/main/java/com/cyberbot/checkers/ui/activity/MainActivity.kt
  app/src/main/java/com/cyberbot/checkers/ui/animator/AnimatedPieceValues.kt
  app/src/main/java/com/cyberbot/checkers/ui/animator/CaptureExplosionAnimator.kt
  app/src/main/java/com/cyberbot/checkers/ui/animator/FullMoveAnimator.kt
  app/src/main/java/com/cyberbot/checkers/ui/animator/MoveScaleAnimator.kt
  app/src/main/java/com/cyberbot/checkers/ui/animator/PieceAnimator.kt
  app/src/main/java/com/cyberbot/checkers/ui/animator/ScaleAnimator.kt
  app/src/main/java/com/cyberbot/checkers/ui/view/CheckersGridView.kt
Labels: documentation

#55 Difficulty settings
  app/src/main/java/com/cyberbot/checkers/preferences/Preferences.kt
  app/src/main/java/com/cyberbot/checkers/ui/activity/GameActivity.kt
  app/src/main/java/com/cyberbot/checkers/ui/activity/MainActivity.kt
  app/src/main/java/com/cyberbot/checkers/ui/activity/SettingsActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#61 Disable immovable entries
  app/src/main/java/com/cyberbot/checkers/ui/activity/GameActivity.kt
  app/src/main/java/com/cyberbot/checkers/ui/view/CheckersGridView.kt
Labels: enhancement

#63 UI improvements
  app/build.gradle
  app/src/main/java/com/cyberbot/checkers/ui/activity/GameActivity.kt
  app/src/main/java/com/cyberbot/checkers/ui/activity/SettingsActivity.kt
  app/src/main/java/com/cyberbot/checkers/ui/view/CheckersGridView.kt
  app/src/main/res/color/chip_text_color.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#57 Win/lose/draw logic
  app/src/main/java/com/cyberbot/checkers/game/GameEnd.java
  app/src/main/java/com/cyberbot/checkers/game/GameEndReason.java
  app/src/main/java/com/cyberbot/checkers/game/Grid.java
Labels: enhancement

#66 Fix the draw result not being displayed
  app/src/main/java/com/cyberbot/checkers/ui/activity/GameActivity.kt
  app/src/main/res/values/strings.xml
Labels: bug

#62 First fully functional release
  .github/workflows/android-release.yml
  .idea/inspectionProfiles/Project_Default.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cyberbot/checkers/game/AiPlayer.java
  app/src/main/java/com/cyberbot/checkers/game/CaptureChain.java
  app/src/main/java/com/cyberbot/checkers/game/Destination.java
  app/src/main/java/com/cyberbot/checkers/game/Grid.java
  app/src/main/java/com/cyberbot/checkers/game/Move.java
  app/src/main/java/com/cyberbot/checkers/game/ai/AiPlayer.java
  app/src/main/java/com/cyberbot/checkers/game/ai/Node.java
  app/src/main/java/com/cyberbot/checkers/game/ai/Tree.java
  app/src/main/java/com/cyberbot/checkers/game/logic/CaptureChain.java
  app/src/main/java/com/cyberbot/checkers/game/logic/Destination.java
  app/src/main/java/com/cyberbot/checkers/game/logic/GameEnd.java
  app/src/main/java/com/cyberbot/checkers/game/logic/GameEndReason.java
  app/src/main/java/com/cyberbot/checkers/game/logic/Grid.java
  app/src/main/java/com/cyberbot/checkers/game/logic/GridEntry.java
  app/src/main/java/com/cyberbot/checkers/game/logic/PieceType.java
  app/src/main/java/com/cyberbot/checkers/game/logic/PlayerNum.java
  app/src/main/java/com/cyberbot/checkers/preferences/Preferences.kt
  app/src/main/java/com/cyberbot/checkers/ui/activity/GameActivity.kt
  app/src/main/java/com/cyberbot/checkers/ui/activity/MainActivity.kt
  app/src/main/java/com/cyberbot/checkers/ui/activity/SettingsActivity.kt
  app/src/main/java/com/cyberbot/checkers/ui/animator/AnimatedPieceValues.kt
  app/src/main/java/com/cyberbot/checkers/ui/animator/CaptureExplosionAnimator.kt
  app/src/main/java/com/cyberbot/checkers/ui/animator/FullMoveAnimator.kt
  app/src/main/java/com/cyberbot/checkers/ui/animator/MoveScaleAnimator.kt
  app/src/main/java/com/cyberbot/checkers/ui/animator/PieceAnimator.kt
  app/src/main/java/com/cyberbot/checkers/ui/animator/ScaleAnimator.kt
  app/src/main/java/com/cyberbot/checkers/ui/utils.kt
  app/src/main/java/com/cyberbot/checkers/ui/view/CheckersGridView.kt
  app/src/main/res/color/chip_text_color.xml
  app/src/main/res/layout/activity_game.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/cyberbot/checkers/game/logic/GridEntryTest.java
  app/src/test/java/com/cyberbot/checkers/game/logic/GridTest.java
Labels: release
